defaults: &defaults
  :log_level: warn
  :redis:
    :port: 6379
  :sqlite:
    :file: db/app.sqlite

:development:
  <<: *defaults
  :log_level: debug

:test:
  <<: *defaults
  :redis:
    :port: 6380

:production:
  <<: *defaults
